#
#. This config file adds support for Netlify CMS, exposed at /admin on the running site.
# In order to use this on your site,
#. 1) replace instances of "exampleSite/......" with the appropriate paths, relative from repository root.
#. 2) replace repo path in `backend` settings, and set branch to master.
#  3) Optionally enable the [editor workflow](https://www.netlifycms.org/docs/configuration-options/#publish-mode) which uses PRs for content changes
#  4) Optionally enable [open authoring](https://www.netlifycms.org/docs/open-authoring/) for community sites, which requires #3
#
#

backend:
  name: git-gateway
  repo: mo-gaafar/cuert-frontend
  branch: main
  publish_mode: editorial_workflow
  site_domain: https://cu-eco.org
  display_url: https://cu-eco.org
  logo_url: https://cu-eco.org/favicon.ico

media_folder: "v1/static/img" # Folder where user uploaded files should go
public_folder: "/img" # The src attribute for uploaded files will begin with this folder name

collections: # A list of collections the CMS should be able to edit
  - name: "slider"
    label: "Slider"
    widget: "list"
    folder: "v1/data/carousel"
    extension: yaml
    format: yaml
    create: true
    slug: "{{day}}-{{hour}}-{{minute}}-{{name}}"
    fields:
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default = false,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Weight", name: "weight", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "News" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI, ie.: "New Post"
    folder: "v1/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{hour}}-{{minute}}-{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default = false,
        }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "Cars"
    label: "Cars"
    folder: "v1/content/cars"
    create: true
    slug: "{{day}}-{{hour}}-{{minute}}-{{name}}"
    fields:
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default = false,
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Class",
          name: "class",
          widget: "select",
          options: ["Prototype", "Urban Concept"],
          default: "Prototype",
        }
      - { label: "Year", name: "year", widget: "number", default: 2021 }
      - { label: "Max Speed", name: "maxSpeed", widget: "number" }
      - {
          label: "Distance per Liter",
          name: "distancePerLiter",
          widget: "number",
        }
      - {
          label: "Achievements",
          name: "achievements",
          widget: "list",
          required: false,
          fields:
            [
              {
                label: "Icon",
                name: "icon",
                widget: "select",
                options:
                  [
                    "🏆 Trophy",
                    "🌟 Award",
                    "🥇 First",
                    "🥈 Second",
                    "🥉 Third",
                  ],
                default: "🏆 Trophy",
              },
              { label: "Year", name: "year", widget: "number" },
              { label: "Achievement", name: "achievement", widget: "string" },
              { label: "Image", name: "image", widget: "image" },
              { label: "Link", name: "link", widget: "string" },
            ],
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "Achievements"
    label: "Achievements"
    folder: "v1/data/testimonials"
    create: true
    slug: "{{day}}-{{hour}}-{{minute}}-{{title}}"
    extension: yaml
    format: yaml
    fields:
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default = false,
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Award Date",
          name: "date",
          widget: "date",
          format: "YYYY-MM-DD",
        }
      - { label: "Image", name: "image", widget: "image" }

      - { label: "Body", name: "awardingBody", widget: "string" }
      - { label: "Weight", name: "weight", widget: "number", default: 100 }
  #  - name: "Team Members"
  #    label: "Team Members"
  #    folder: "v1/content/team"
  #    create: true
  #    slug: "{{day}}-{{hour}}-{{minute}}-{{name}}"
  #    fields:
  #      - {
  #          label: "Featured",
  #          name: "featured",
  #          widget: "boolean",
  #          default = false,
  #        }
  #      - { label: "Name", name: "name", widget: "string" }
  #      - { label: "Department", name: "department", widget: "string" }
  #      - {
  #          label: "Graduation Year",
  #          name: "graduationYear",
  #          widget: "number",
  #          default: 2023,
  #        }
  #      - {
  #          label: "Subteam Name",
  #          name: "subteam",
  #          widget: "string",
  #          required: false,
  #        }
  #      - {
  #          label: "Role",
  ##          name: "role",
  #          widget: "select",
  #          options: ["Member", "Head", "Vice Head", "Advisor", "Team Leader"],
  #        }
  #      - { label: "Profile Picture", name: "image", widget: "image" }
  #      - { label: "Bio", name: "bio", widget: "markdown" }
  #      - { label: "Tags", name: "tags", widget: "list", required: false }
  #     - label: "Socials"
  #        name: "socials"
  #        widget: "object"
  #        required: false
  #        fields:
  #          - label: "Linkedin"
  #            name: "linkedin"
  #            required: false
  #            widget: "string"
  #          - label: "Facebook"
  #            name: "facebook"
  #            required: false
  #            widget: "string"
  #          - label: "Instagram"
  #            name: "instagram"
  #            required: false
  #            widget: "string"
  #          - label: "Twitter"
  #            name: "twitter"
  #            required: false
  #            widget: "string"

  - name: "Sponsors"
    label: "Sponsors"
    folder: "v1/data/clients"
    extension: yaml
    format: yaml
    create: true
    slug: "{{day}}-{{hour}}-{{minute}}-{{name}}"
    fields:
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default = false,
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "image", widget: "image" }
      - { label: "Link", name: "url", widget: "string" }

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - label: "Site Settings"
        name: "general"
        file: "config.yaml"
        extension: yaml
        description: "General Site Settings"
        fields:
          - label: "Global title"
            name: "title"
            widget: "string"

          - label: "Site Url"
            name: "baseURL"
            widget: "string"

          - label: "Theme"
            name: "theme"
            widget: "hidden"
            default: "up-business-theme"

          - label: "Language Code"
            name: "languageCode"
            widget: "hidden"
            default: "en-us"

          - label: "title"
            name: "params.title"
            widget: "string"

          - label: "description"
            name: "params.description"
            widget: "string"

          - label: "images"
            name: "params.images"
            widget: "list"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "logo"
            name: "params.logo"
            widget: "string"

          - label: "themeColor"
            name: "params.favicons.themeColor"
            widget: "string"

          - label: "backgroundColor"
            name: "params.favicons.backgroundColor"
            widget: "string"

          - label: "faviconColor"
            name: "params.favicons.faviconColor"
            widget: "string"

          - label: "linkedin"
            name: "params.social.handles.linkedIn"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Link"
                name: "link"
                widget: "string"

          - label: "instagram"
            name: "params.social.handles.instagram"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Link"
                name: "link"
                widget: "string"

          - label: "facebook"
            name: "params.social.handles.facebook"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Link"
                name: "link"
                widget: "string"

          - label: "twitter"
            name: "params.social.handles.twitter"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Link"
                name: "link"
                widget: "string"

          - label: "location"
            name: "location"
            widget: "list"
            fields:
              - label: "Location"
                name: "location"
                widget: "string"

          - label: "contact"
            name: "contact"
            widget: "list"
            fields:
              - label: "Contact"
                name: "contact"
                widget: "string"

          - label: "copyright"
            name: "params.copyright"
            widget: "string"

          - label: "Home"
            name: "menus.main.home"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Weight"
                name: "weight"
                widget: "number"

          - label: "How we work"
            name: "menus.main.how-we-work"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Weight"
                name: "weight"
                widget: "number"

          - label: "Our team"
            name: "menus.main.our-team"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Weight"
                name: "weight"
                widget: "number"

          - label: "Achievements"
            name: "menus.main.achievements"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Weight"
                name: "weight"
                widget: "number"

          - label: "News"
            name: "menus.main.news"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Weight"
                name: "weight"
                widget: "number"

          - label: "Contact Us"
            name: "menus.buttons.contact-us"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Weight"
                name: "weight"
                widget: "number"
              - label: "Pre"
                name: "pre"
                widget: "string"
